# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 500000

runner: "parallel"
batch_size_run: 8
buffer_size: 5000
batch_size: 32    # original: 64

n_heads: 2
atten_dim: 64

double_q: True

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
mac: "roma_mac"
agent: "roma"
agent_output_type: q

learner: "roma_learner"
mixer: "attn_mix"
mixing_embed_dim: 32
hypernet_embed: 64
lr: 0.001 # Learning rate for agents
#td_lambda: 0.6 # 0.3 for 6h_vs_8z
optimizer: 'adam'
q_lambda: False

latent_dim: 3
kl_loss_weight: 0.0001
h_loss_weight: 0.0001
var_floor: 0.002
NN_HIDDEN_SIZE: 16
dis_loss_weight: 0.001
dis_time: 0
soft_constraint_weight: 1.0
roma_raw: False


dis_sigmoid: False

# rnn layer normalization
use_layer_norm: False

# orthogonal init for DNN
use_orthogonal: False
gain: 0.01

# Priority experience replay
use_per: False
per_alpha: 0.6
per_beta: 0.4
return_priority: False

name: "1203_roma_5"